linters:
  enable-all: true
  disable:
    - depguard
    - exhaustivestruct
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - goerr113
    - gofumpt
    - gomnd
    - nlreturn
    - varnamelen
