name: Build

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    paths:
      - "go.*"
      - "**/*.go"
      - ".github/workflows/*.yml"
      - "build/lint.sh"
      - ".goreleaser.yaml"
      - ".golangci.yml"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - name: Install dependencies
        run: |
          go get .
      - name: Build
        run: go build -v ./...
      - name: Lint
        run: make lint
      name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          install-only: true
      - name: Validate goreleaser
        run: goreleaser check
      - name: Release new tag
        if: startsWith(github.ref, 'refs/tags/')
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
